catcollector/urls.py
from django.contrib import admin
from django.urls import path, include # include allows us to include additional url conf

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    # NOTE: we set up routes using the path method
    # NOTE: the "root path" in django is represented by an empty string
]

main_app/urls.py
from django.urls import path
from . import views

# NOTE: django ONLY uses GET and POST; there is not REST in django; we never do DELETE, PUT
# NOTE: in django updating and deleting will be conducted using POST request
# NOTE: django paths NEVER begin with a "/"; django prepends this automatically
"""
Examples of deleting and updating
path('cats/<int:cat_id>/remove_cat/'),
path('cats/<int:cat_id>/remove_cat/'),
"""

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='cats_index'),
    path('cats/<int:cat_id>/', views.cat_detail, name='cat_detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cat_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('cats/<int:cat_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toy_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toy_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toy_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toy_delete'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Toy(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)
  
  def __str__(self):
      return self.name
  
  def get_absolute_url(self):
    return reverse('toy_detail', kwargs={'pk': self.id})   

class Cat(models.Model):
    name = models.CharField(max_length=100) # varchar datatype
    breed = models.CharField(max_length=100) # varchar datatype
    description = models.TextField(max_length=250) # text datatype
    age = models.IntegerField(default=0)

    def __str__(self):
        return self.name
    
    # this instance method returns a url for the detail page for each instance
    # this concept is based on the "fat models skinny controllers"
    def get_absolute_url(self):
        return reverse('cat_detail', kwargs={'cat_id': self.id})

class Feeding(models.Model):
    MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
    )

    date = models.DateField('feeding date')
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0][0], verbose_name='meal type')
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"
        # NOTE: when a field has a choices kw arg, we can use the get_<fieldname>_display()
        # method to display the human friendly version of the single character value
        # This is called field choices in django
        # https://docs.djangoproject.com/en/4.1/ref/models/fields/
    class Meta:
        ordering = '-date',

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.shortcuts import render, redirect
# NOTE: class-based views are classes that create view function objects containing
# pre-defined controller logic commonly used for basic CRUD operations
# their main benefit is to provide convenience to developers
from .models import Cat, Toy
from .forms import FeedingForm

# we use this file to define controller logic
# NOTE: each controller is defined using either a function or a class
# NOTE responses are returned from view functions
# NOTE: all views function take at least one required positional argument: request

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cats_index(request):
    cats = Cat.objects.all()
    return render(request, 'cats/index.html', {'cats': cats})

# NOTE: url params are explicitly passed to view functions seperate from the request object
def cat_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
        'cat': cat, 
        'feeding_form': feeding_form
    })


def add_feeding(request, cat_id):
    # create a new model instance of feeding
    form = FeedingForm(request.POST) # {'meal': 'B', date: '2023-04-05', cat_id: None}
    # validate user input provided from form submission
    if form.is_valid():
       new_feeding = form.save(commit=False) # create an in-memory instance without saving to the database
       new_feeding.cat_id = cat_id # attach the associated cat's id to the cat_id attr
       new_feeding.save() # this will save a new feeding to the database
    # as long as form is valid we can associate the related cat to the new feeding
    # return a redirect response to the client
    return redirect('cat_detail', cat_id=cat_id)

class CatCreate(CreateView):
    model = Cat
    fields = '__all__' # adds all the fields to the corresponding ModelForm
    template_name = 'cats/cat_form.html'
    # success_url = '/cats/'

class CatUpdate(UpdateView):
    model = Cat
    fields = ('description', 'age') # tuples are preferred over lists for the field attr
    template_name = 'cats/cat_form.html'
    # tuples are lightweight and use less space (memory)

class CatDelete(DeleteView):
    model = Cat
    success_url = '/cats/'
    template_name = 'cats/cat_confirm_delete.html'

class ToyCreate(CreateView):
    model = Toy
    fields = '__all__'
    template_name = 'toys/toy_form.html'

class ToyList(ListView):
    model = Toy
    template_name = 'toys/toy_list.html'

class ToyDetail(DetailView):
    model = Toy
    template_name = 'toys/toy_detail.html'
    
class ToyUpdate(UpdateView):
    model = Toy
    fields = '__all__'
    template_name = 'toys/toy_form.html'

class ToyDelete(DeleteView):
    model = Toy
    success_url = '/toys/'
    template_name = 'toys/toy_confirm_delete.html'

main_app/templates/about.html
{% extends 'base.html' %}
<!-- Try extending base.html here -->

{% block title %}
<title>About the Cat Collector</title>
{% endblock %}


<!-- Try wrapping this in a content block -->
{% block content %}
    <h1>About the Cat Collector</h1>
    <p>This is a template</p>
{% endblock %}

main_app/templates/base.html
<!-- NOTE: load static informs the view engine that static assets are needed here -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Materialize jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    
    <!-- Example of how we'd do this with javascript static files -->
    <!-- <script defer src="{% static 'js/script.js' %}"></script> -->
    {% block title %}
    <title>Cat Collector</title>
    {% endblock %}
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper deep purple">
                <a class="left brand-logo" href="{% url 'home' %}">Cat Collector</a>
                <ul class="right">
                    <li>
                        <a href="{% url 'about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'cats_index' %}">View All Cats</a>
                    </li>
                    <li>
                        <a href="{% url 'cat_create' %}">Add a Cat</a>
                    </li>
                    <li>
                        <a href="{% url 'toys_index' %}">View All Toys</a>
                    </li>
                    <li>
                        <a href="{% url 'toy_create' %}">Add a Toy</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %} 
        {% endblock %}
    </main>
    <footer class="page-footer deep purple">
        <p>Copyright &copy; All Rights Reserved Cat Collector 2023</p>
    </footer>
</body>
</html>

main_app/templates/cats/cat_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Are you sure you want to delete {{ object.name }}?</title>
{% endblock %}


{% block content %}
<h1>Are you sure you want to delete {{ object.name }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.name }}" class="btn red">
    <a href="{% url 'cats_detail' object.id %}" class="btn blue">No - Cancel</a>
</form>
{% endblock %}

main_app/templates/cats/cat_form.html
{% extends 'base.html' %}

{% block title %}
    {% if object %}
        <title>Update {{ object.name }}</title>
    {% else %}
        <title>Add a Cat</title>
    {% endif %}
{% endblock %}

{% block content %}
    {% if object %}
        <h1>Update {{ object.name }}</h1>
    {% else %}
        <h1>Create Cat</h1>
    {% endif %}


<form method="POST">
    {% csrf_token %}
    <table>        
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn blue">
</form>

{% endblock %}

main_app/templates/cats/detail.html
{% extends 'base.html' %}

{% block title %}
 <title>Cat Detail</title>
{% endblock %}

{% block content %}
<h1>Cat Detail</h1>

<!-- NOTE: DTL (Django Template Language) is NOT Python, albeit it looks very "Pythonic" -->

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ cat.name }}</span>
                <p>Breed: {{ cat.breed }}</p>
                <p>Description: {{ cat.description }}</p>
                {% if cat.age > 0 %}
                    <p>Age: {{cat.age}}</p>
                {% else %}
                    <p>Age: Kitten</p>
                {% endif %}
            </div>
            <div class="card-action">
                <a href="{% url 'cat_update' cat.id %}">Update</a>
                <a href="{% url 'cat_delete' cat.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' cat.id %}" method="POST">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" value="Add Feeding" class="btn blue">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in cat.feeding_set.all %}
                    <tr>
                        <td>{{ feeding.date }}</td>
                        <td>{{ feeding.get_meal_display }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


<script>
    // DOM Element references
    const datePickerEl = document.getElementById('id_date');
    const formSelectEl = document.getElementById('id_meal');

    // Materialize init for DatePicker and FormSelect
    M.Datepicker.init(datePickerEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
    M.FormSelect.init(formSelectEl);
</script>

{% endblock %}

main_app/templates/cats/index.html
{% extends 'base.html' %}

{% block title %}
 <title>Cat List</title>
{% endblock %}

{% block content %}
<h1>Cat List</h1>

<!-- NOTE: DTL (Django Template Language) is NOT Python, albeit it looks very "Pythonic" -->
{% for cat in cats %}
<a href="{% url 'cat_detail' cat.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ cat.name }}</span>
            <p>Breed: {{ cat.breed }}</p>
            <p>Description: {{ cat.description }}</p>
            {% if cat.age > 0 %}
                <p>Age: {{cat.age}}</p>
            {% else %}
                <p>Age: Kitten</p>
            {% endif %}
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/toys/toy_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Are you sure you want to delete {{ object.name }}?</title>
{% endblock %}


{% block content %}
<h1>Are you sure you want to delete {{ object.name }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete {{ object.name }}" class="btn red">
    <a href="{% url 'cat_detail' object.id %}" class="btn blue">No - Cancel</a>
</form>
{% endblock %}

main_app/templates/toys/toy_detail.html
{% extends 'base.html' %}

{% block title %}
 <title>Toy Detail</title>
{% endblock %}

{% block content %}
<h1>Toy Detail</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">A <span class="{{toy.color.lower}}-text">{{toy.color.capitalize}}</span> {{ toy.name }}</span>
    </div>
    <div class="card-action">
        <a href="{% url 'toy_update' toy.id %}">Update</a>
        <a href="{% url 'toy_delete' toy.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/toys/toy_form.html
{% extends 'base.html' %}

{% block title %}
    {% if object %}
        <title>Update {{ object.name }}</title>
    {% else %}
        <title>Add a Toy</title>
    {% endif %}
{% endblock %}

{% block content %}
    {% if object %}
        <h1>Update {{ object.name }}</h1>
    {% else %}
        <h1>Create Toy</h1>
    {% endif %}


<form method="POST">
    {% csrf_token %}
    <table>        
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn blue">
</form>

{% endblock %}

main_app/templates/toys/toy_list.html
{% extends 'base.html' %}

{% block title %}
 <title>Toy List</title>
{% endblock %}

{% block content %}
<h1>Toy List</h1>

{% for toy in object_list %}
<a href="{% url 'toy_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">A <span class="{{toy.color.lower}}-text">{{toy.color.capitalize}}</span> {{ toy.name }}</span>
        </div>
    </div>
</a>
{% endfor %}

{% endblock %}